/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bj58_zlsf_impl_FaceIdentifyRecoger */

#ifndef _Included_com_bj58_zlsf_impl_FaceIdentifyRecoger
#define _Included_com_bj58_zlsf_impl_FaceIdentifyRecoger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bj58_zlsf_impl_FaceIdentifyRecoger
 * Method:    LoadDictionary
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bj58_zlsf_impl_FaceIdentifyRecoger_LoadDictionary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_bj58_zlsf_impl_FaceIdentifyRecoger
 * Method:    DetectAndRecogFaceFromImage
 * Signature: ([BI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bj58_zlsf_impl_FaceIdentifyRecoger_DetectAndRecogFaceFromImage
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
